_target_: src.models.components.nets.transformers.dit.DiT
depth: 12
block_size: ${data.block_size}
hidden_size: ${model.diffusion.encoder.embedding_dim}
output_size: ${model.diffusion.encoder.embedding_dim}
num_heads: 12

