#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=basic_diff
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=20:00:00
#SBATCH --output=$HOME/discrete_diffusion/slurm_outputs/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Your job starts in the directory where you call sbatch
cd $HOME/discrete_diffusion
# Activate your environment
source activate fomo
# Run your code
srun python src/sample.py experiment=roc_mulan_adaptive.yaml ckpt_path="/gpfs/home4/nmidavaine1/discrete_diffusion/logs/diffusion_logs/roc_mulan_adaptive/20250502_192340/checkpoint_4624-800000thisone.ckpt" ++model_name=roc_mulan_adaptive +setting=test_mode +n_steps=2000 "++model.diffusion.gamma.gamma_shape=[64, 1]" "+sampling_mode=[marginal, star]" +use_uniform=True 