_target_: src.models.backbones.transformer_model2.TransformerNetModel2

in_channels: 128
model_channels: 128
out_channels: 128
num_res_blocks: 40000 #not used
attention_resolutions: 0,1
dropout: 0.1
channel_mult: 1,2,2,2
num_classes: null
use_checkpoint: false
num_heads: 4
num_heads_upsample: -1
use_scale_shift_norm: true
config_name:  bert-base-uncased
training_mode: e2e
vocab_size: ${data.vocab_size}
experiment_mode: lm
logits_mode: 1
embedding_model: false
nfdm: true
attn_implementation: eager
#layer_norm_eps: 1e-4