_target_: src.models.language_diff_module.DiffusionModule

diffusion:  #define the diffusion seperately in the experiment config
  _target_: src.models.diffusions.NeuralDiffusion
  pred: debug
  affine: debug
  vol: debug
  encoder: debug
  decoder: debug

compute_diffusion_loss: true
compute_prior_loss: false
compute_reconstruction_loss: true
reconstruction_loss_type: diff_anchor

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0

scheduler: null

# compile model for faster training with pytorch 2.0
compile: false