defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - _self_
  - word_sampler
  - collapse

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/elbo"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/elbo"
  patience: 100
  mode: "min"

model_summary:
  max_depth: 2
