# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: null
  filename: "checkpoint-{step:06d}"
  verbose: true
  save_last: True
  save_top_k: -1
  auto_insert_metric_name: False
  save_weights_only: False
  every_n_train_steps: 10000  # Save checkpoint every 500 steps
  every_n_epochs: null  # Disable epoch-based saving
  save_on_train_epoch_end: False