# @package _global_

defaults:
  - _self_
  - data: text8 # choose datamodule with `test_dataloader()` for evaluation
  - model: language_diff_module
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: default

  - experiment: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /teamspace/studios/this_studio/discrete_diffusion/logs/epoch_012.ckpt
