# @package _global_

defaults:
  - _self_
  - data: text8 # choose datamodule with `test_dataloader()` for evaluation
  - model: language_diff_module
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "sample"

tags: ["dev"]

get_sde: true
get_ode: false
n_steps: 150
batch_size: 2

debug: false
clamping: false
top_k: false
k: 5
top_p: false
p: 0.9
temperature: 1.0

compute_ani: false

# passing checkpoint path is necessary for evaluation
ckpt_path: /teamspace/studios/this_studio/discrete_diffusion/logs/last_new.ckpt