# @package _global_

defaults:
  - _self_
  - data: e2e # choose datamodule with `test_dataloader()` for evaluation
  - model: language_diff_module
  - callbacks: default
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - experiment: null


model_name: roc_static
ckpt_path: null

# task name, determines output directory path
task_name: "train"
plot_time_and_loss: False

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

seed: 42

