_target_: src.models.ndm.ndm.NeuralDiffusion

transform: 
  _target_: src.models.ndm.components.transform.AffineTransformHalfNeural
  model: debug

gamma:
  _target_: src.models.ndm.components.gamma.GammaMuLAN #GammaTheirs
  gamma_shape: [64, 1]

vol_eta:
  _target_: src.models.ndm.components.vol_eta.VolatilityEtaOne

pred:
  _target_: src.models.ndm.components.predictor.Predictor
  model: debug
