_target_: src.models.components.predictor.Predictor

model:
  _target_: src.models.components.nets.transformers.nano_gpt.GPT
  config:
    block_size: 1024
    vocab_size: ${data.text8.vocab_size} # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
    n_layer: 12
    n_head: 12
    n_embd: 768
    output_size: ${model.components.encoder.embedding_dim} * 2 #1536
    dropout: 0.0
    bias: true # True: bias in Linears and LayerNorms, like GPT-2. False: a bit better and faster