# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  limit_train_batches: 5
  limit_val_batches: 0
  accelerator: gpu
  #profiler: "simple"
  #profiler: "advanced"
  profiler:
    _target_: pytorch_lightning.profilers.PyTorchProfiler
    with_stack: false                     # Include stack traces
    profile_memory: true                  # Use memory profiler

  

get_memory_snapshot: true 